// 레이아웃 (서버)

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ClientLayout from "./ClientLayout";
import client from "@/lib/backend/client";
import { cookies } from "next/headers";

const pretendard = localFont({
  src: "./../../node_modules/pretendard/dist/web/variable/woff2/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const response = await client.GET("/user/me", {
    headers: {
      cookie: (await cookies()).toString(),
    },
  });

  const me = response.data
    ? response.data
    : {
        id: 0,
        username: "",
        createDate: "",
        modifyDate: "",
      };

  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <body
        className={`${pretendard.className} antialiased flex flex-col min-h-[100dvh]`}
      >
        <ClientLayout me={me}>{children}</ClientLayout>
      </body>
    </html>
  );
}
