spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ca71b65f4178ea7b680d19bdda8d3231
          google:
            clientId: 87515489820-nb4ga71br7e8i09kegqebb1ojv7m8j1h.apps.googleusercontent.com
            client-secret: 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

custom:
  jwt:
    secretKey: asdlkjh1o2e98aslkdjqa09sd8ql2k34nj0a9sdfalksne102e8alksdj
